version: '3'

services:
  medo_nvenc_video_encoder:
    container_name: nvenc_video_encoder
    user: root
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    runtime: nvidia
    privileged: true
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
    image: jrottenberg/ffmpeg:5.1-nvidia
    volumes:
      - ${INPUT_FOLDER}:/input
      - ${OUTPUT_FOLDER}:/output
      - /mnt/docker_data:/mnt/docker_data
      - ./convert_videos.sh:/convert_videos.sh
      - ./tmp:/tmp
      - ./resume_state:/resume_state
    entrypoint: ["/bin/bash", "/convert_videos.sh"]