version: '3'

services:
  nvenc_video_encoder:
    container_name: nvenc_video_encoder
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    runtime: nvidia
    privileged: true
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
    image: jrottenberg/ffmpeg:5.1-nvidia
    volumes:
      - TZ=Europe/Paris
      - ${INPUT_FOLDER}:/input
      - ${OUTPUT_FOLDER}:/output
      - ./convert_videos.sh:/convert_videos.sh
      - ./resume_state:/resume_state:rw
      - ${EXTRA_VOLUME_1:-/dev/null}:${EXTRA_VOLUME_1_TARGET:-/dev/null}
      - ${EXTRA_VOLUME_2:-/dev/null}:${EXTRA_VOLUME_2_TARGET:-/dev/null}
    entrypoint: ["/bin/bash", "-c"]
    command:
      - |
        # Create the medo user with UID and GID 1001
        useradd -u 1000 -m medo 2>/dev/null || true
        groupadd -g 1000 medo 2>/dev/null || true
        usermod -aG medo medo

        # Change ownership of the directories
        chown -R medo:medo /input /output /resume_state

        # Switch to the medo user and execute the script
        exec runuser -u medo -- /convert_videos.sh
